### ISSUE TITLE
[BUG] Damage fields with the same damage type are grouped despite differing contexts

### ISSUE THREAD

**Issue by lparkjordan** [MangoFVTT/fvtt-ready-set-roll-5e#449]
**Description**
When an attack is rolled, all damage fields with the same damage type are grouped into a single header in the damage card display. This can sometimes result in incorrect context labelling as well. 

For example, I have a weapon with three damage fields. If I set them all to piercing damage, they appear as a single field in the damage roll:

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/6636724/2bc965cd-15ba-4257-9c34-b701928d49d2)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/6636724/d3142f2d-c898-46fe-a525-b0ff92c847ba)

If I change the third field to have a different damage type, I end up with two fields in the roll, with the second incorrectly labeled:

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/6636724/0a375e17-af26-4f4d-8931-31a34d036f15)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/6636724/222b41c7-e4af-49b3-9b40-5df87670864e)

If I change all three fields to have different damage types, the damage card displays all three categories, as expected:

![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/6636724/96b13a5d-8a79-4625-83f2-8acdc09996ab)
![image](https://github.com/MangoFVTT/fvtt-ready-set-roll-5e/assets/6636724/67d637ac-9c0d-4d9b-9dcd-d1d5108fae1d)

All three damage rolls are enabled in the quick roll settings.

**Steps to Reproduce**
1. Create an item with multiple damage fields, all with the same damage type and different contexts.
2. Roll the item with default settings. 
3. Expand the damage displayed in the chat card.

**Versions**
 - Module: [3.1.0]
 - dnd5e: [3.2.1]
 - Foundry: [11.315]

**Other Modules**
Tidy 5e Sheets 4.4.1

**Comment by MangoFVTT** [comment]
This is a known issue and is caused entirely by the base dnd5e system and the fact that it force merges fields that have the same damage type into the same damage value. It cannot be fixed by RSR until this ticket: https://github.com/foundryvtt/dnd5e/issues/3652#issuecomment-2138370780 is resolved.

Closing this as duplicate since it has been brought up several times before.

**Comment by nschoenwald** [comment]
@MangoFVTT The issue within the dnd5e game system has been resolved. Could this issue be re-opened?

**Comment by MangoFVTT** [comment]
@nschoenwald see my comment on https://github.com/foundryvtt/dnd5e/issues/3652#issuecomment-2247360199 as to why this isn't fixed yet. I made a PR to the dnd5e system myself to actually resolve this issue so that RSR can finally have the non-aggregated damage rolls working again.

**Comment by RalphTheBard** [comment]
@MangoFVTT it seems that this still repros in 4.0.2.

Repro steps:
1. Disabled all add-ons.
2. Created a feature on an npc that produces two instances of damage with the same type (piercing).
3. Rolled damage.
4. Piercing damage is aggregated in one roll.

**Comment by RalphTheBard** [comment]
Might be dependent on this work item, currently scheduled for 4.1.0: https://github.com/foundryvtt/dnd5e/issues/3357
