### ISSUE TITLE
[BUG] Ready Set Roll prevents Misty Step animations from working in Automated Animations

### ISSUE THREAD

**Issue by nschoenwald** [MangoFVTT/fvtt-ready-set-roll-5e#552]
**Steps to Reproduce**
Install the modules. Cast Misty Step. No rangefinder is shown, no animation is triggered.
Without Ready Set Roll, casting Misty Step correctly causes the rangefinder to show and the token to teleport after clicking the target space.
This used to work in the past, so seems to be a recent regression.

**Versions**
 - Module: 3.4.2
 - dnd5e: 4.1.2
 - Foundry: 12.331

**Other Modules**
Automated Animations 4.2.83
Sequencer 3.4.7

**Comment by MangoFVTT** [comment]
@nschoenwald I don't use Automated Animations myself so it would be useful to have more info on any errors or such that are showing up in the log.

**Comment by nschoenwald** [comment]
> @nschoenwald I don't use Automated Animations myself so it would be useful to have more info on any errors or such that are showing up in the log.

Unfortunately there are no console errors, the animation just fails to trigger when RSR is enabled.

<img width="292" alt="image" src="https://github.com/user-attachments/assets/ef5a86e7-ff11-4681-8f69-baca02376476" />

This is the only thing in the log when casting Misty Step.

**Comment by nschoenwald** [comment]
If you want to test, you just need Automated Animations and the free JB2A module. Misty Step should be configured by default, no need to add a configuration or anything like that.

**Comment by DudeAndre** [comment]
Oh, I thought it was an A-A issue, because that module was on maintenance mode only. Hope it can get fixed from the RSR side then.

**Comment by DudeAndre** [comment]
I tried and asked Ripper93 (who is now in charge of A-A development) if he could collaborate on this, but he's not gonna do more updates for A-A untile V 13. So I really hope you can fix this. Fingers crossed

**Comment by DudeAndre** [comment]
By the way the conflict is not limited to misty step, other spells with animations that works with RSR de-activated cease to work when it is activated. For example Absorb Elements. Unfortunately the console only gives this feedback 
![image](https://github.com/user-attachments/assets/dd8eec23-96ee-4aa7-bbe7-2f4b7b22b9a4)

**Comment by MangoFVTT** [comment]
Issue is resolved and will be in the next release. This "fix" causes an issue where certain activities will trigger subsequent actions that are not needed by RSR. Unfortunately, there is no easy way to avoid this while also allowing AA to work. RSR would usually skip the post use hook to avoid this unnecessary popups, but AA uses the post use hook to trigger animations.

**Comment by nschoenwald** [comment]
> Issue is sort of resolved and will be in the next release. This "fix" causes an issue where certain activities will trigger subsequent actions that are not needed by RSR. Unfortunately, there is no easy way to avoid this while also allowing AA to work. RSR would usually skip the post use hook to avoid this unnecessary popups, but AA uses the post use hook to trigger animations.

This works very weirdly now. When I do a regular weapon attack, RSR rolls the attack randomly, but I still get the default pop-up to roll the attack. However, when clicking to roll from that pop-up, a die from dice so nice rolls but nothing happens in the chat card, which already has the RSR roll result.

**Comment by nschoenwald** [comment]
> @nschoenwald this is the issue i mentioned:
> 
> > This "fix" causes an issue where certain activities will trigger subsequent actions that are not needed by RSR. Unfortunately, there is no easy way to avoid this while also allowing AA to work. RSR would usually skip the post use hook to avoid this unnecessary popups, but AA uses the post use hook to trigger animations.
> 
> You can safely close those popups without rolling and RSR will work as normal. There is no way for me to remove those without also removing AA's animations. I would suggest to the maintainer of AA to add a clause to their post use hook that returns false if RSR is active, so as to block those popups.

Honestly the user experience is much worse this way than it was before the new RSR update. 
Ripper won't add features to AA until the V13 update so with the current versions of RSR and AA, the user experience is confusing and buggy :/

**Comment by DudeAndre** [comment]
> @nschoenwald this is the issue i mentioned:
> 
> > This "fix" causes an issue where certain activities will trigger subsequent actions that are not needed by RSR. Unfortunately, there is no easy way to avoid this while also allowing AA to work. RSR would usually skip the post use hook to avoid this unnecessary popups, but AA uses the post use hook to trigger animations.
> 
> You can safely close those popups without rolling and RSR will work as normal. There is no way for me to remove those without also removing AA's animations. I would suggest to the maintainer of AA to add a clause to their post use hook that returns false if RSR is active, so as to block those popups.

If it's a small easy thing I could ask Ripper in his discord to give it a try, and maybe he will. If it's a huge undertanking I'm sure he won't though. Do you have an idea how big this fix is?

**Comment by DudeAndre** [comment]
And of course thank you for this workaround, I'm not sure I'll use it, but at least you tried.

**Comment by nschoenwald** [comment]
> > @nschoenwald this is the issue i mentioned:
> > > This "fix" causes an issue where certain activities will trigger subsequent actions that are not needed by RSR. Unfortunately, there is no easy way to avoid this while also allowing AA to work. RSR would usually skip the post use hook to avoid this unnecessary popups, but AA uses the post use hook to trigger animations.
> > 
> > 
> > You can safely close those popups without rolling and RSR will work as normal. There is no way for me to remove those without also removing AA's animations. I would suggest to the maintainer of AA to add a clause to their post use hook that returns false if RSR is active, so as to block those popups.
> 
> If it's a small easy thing I could ask Ripper in his discord to give it a try, and maybe he will. If it's a huge undertanking I'm sure he won't though. Do you have an idea how big this fix is?

I posted in the discord now, we'll see what the chances are for a fix.

<img width="1039" alt="image" src="https://github.com/user-attachments/assets/8d40ff35-f065-4137-bf82-a7555b6327f1" />

**Comment by MangoFVTT** [comment]
It's a very simple fix, one line of code really. Basically `return game.modules.get("ready-set-roll-5e")?.active ?? false;` at the end of the dnd5e.postUseActivity hook after animations have triggered.

**Comment by DudeAndre** [comment]
Thanks, I'll try writing to him. Cheers

**Comment by theripper93** [comment]
I will make an exception for the current version and add this fix, but be aware that the V13 version will have all module exceptions removed as i expect modules that interfere with the system to mantain the hook workflow the same.

**Comment by nschoenwald** [comment]
> I will make an exception for the current version and add this fix, but be aware that the V13 version will have all module exceptions removed as i expect modules that interfere with the system to mantain the hook workflow the same.

Awesome, thank you!!

**Comment by DudeAndre** [comment]
Thanks to you both!

**Comment by DudeAndre** [comment]
Ripper fixed A-A and all the animations gets triggered, now Mango can you remove the pop-ups?

**Comment by MangoFVTT** [comment]
> Ripper fixed A-A and all the animations get triggered, now Mango could you remove the pop-ups?

There's nothing further to be fixed on my side. There hasn't been a release of AA yet (last one i see is 2 weeks ago), so it's still pending that release.

**Comment by DudeAndre** [comment]
![image](https://github.com/user-attachments/assets/0387b5fd-0165-49e1-b7dd-968d73faf23d)

**Comment by MangoFVTT** [comment]
Well I took a look at the update and ripper made the wrong change 😅 hence why the popups are still showing. The hook returns true by default anyway so returning true when RSR is active does nothing different.

![Image](https://github.com/user-attachments/assets/7c677fe9-a16b-46d9-b45f-31d122d02c39)

**Comment by DudeAndre** [comment]
Sigh

**Comment by MangoFVTT** [comment]
Spoke with @theripper93 about this and we discovered the issue is caused by a race condition where the RSR post use blocks other post use hooks if they are registered after it, but not if they are registered before. I've pushed a more comprehensive fix (thanks to ripper's suggestion) which should no longer interfere with any other post use from other modules, and fully fix this issue without the annoying pop-ups.

**Comment by nschoenwald** [comment]
Is the Misty Step preset working for anyone with the last versions of both modules? It does not work for me still, but I have not been able to test with all other modules disabled yet.

**Comment by DudeAndre** [comment]
> Spoke with [@theripper93](https://github.com/theripper93) about this and we discovered the issue is caused by a race condition where the RSR post use blocks other post use hooks if they are registered after it, but not if they are registered before. I've pushed a more comprehensive fix (thanks to ripper's suggestion) which should no longer interfere with any other post use from other modules, and fully fix this issue without the annoying pop-ups.

Great, again thanks to you both

**Comment by DudeAndre** [comment]
So here's the situation:

RSR 3.4.5 and A-A 5.0.2 or A-A 5.0.3 = all animations are triggered, but attacks and damage activities generate pop-ups
RSR 3.4.6 and A-A 5.0.2 or A-A 5.0.3= attacks and damage activities DO NOT generate pop-ups, but not all animations are triggered: misty step but also counterspell and other on token with no roll like absorb element...

**Comment by MangoFVTT** [comment]
That's very odd, testing right now with just RSR and AA and all my animations seem to trigger just fine and without pop-ups:

![Image](https://github.com/user-attachments/assets/a2fea8f9-2ccc-4094-bb20-5ce739d30cd1)

**Comment by MangoFVTT** [comment]
If either of you is comfortable with editing script files a bit, run a test for me if you could:

1. make sure your foundry is completely closed
2. go to `<your userdata folder>/modules/ready-set-roll-5e/src/utils/hooks.js`
3. open it in a text editor (any will do) and go down to line 142 which should read as follows:

```javascript
setTimeout(() => {
      Hooks.on(HOOKS_DND5E.POST_USE_ACTIVITY, (activity, usageConfig, results) => {
             return false;
       });
}, 1000);
````
4. change the number at the bottom to something bigger like 10000

```javascript
setTimeout(() => {
      Hooks.on(HOOKS_DND5E.POST_USE_ACTIVITY, (activity, usageConfig, results) => {
             return false;
       });
}, 10000);
````
5.  save and close the file, then run foundry again and test the animations
6. if that doesn't work, try again with even bigger numbers, give it a few tries without exceeding crazy values like a million

**Comment by nschoenwald** [comment]
> If either of you is comfortable with editing script files a bit, run a test for me if you could:
> 
>     1. make sure your foundry is completely closed
> 
>     2. go to `<your userdata folder>/modules/ready-set-roll-5e/src/utils/hooks.js`
> 
>     3. open it in a text editor (any will do) and go down to line 142 which should read as follows:
> 
> 
> setTimeout(() => {
>       Hooks.on(HOOKS_DND5E.POST_USE_ACTIVITY, (activity, usageConfig, results) => {
>              return false;
>        });
> }, 1000);
> 
>     4. change the number at the bottom to something bigger like 10000
> 
> 
> setTimeout(() => {
>       Hooks.on(HOOKS_DND5E.POST_USE_ACTIVITY, (activity, usageConfig, results) => {
>              return false;
>        });
> }, 10000);
> 
>     5. save and close the file, then run foundry again and test the animations
> 
>     6. if that doesn't work, try again with even bigger numbers, give it a few tries without exceeding crazy values like a million and try to find the smallest value at which it works for you

I tested Misty Step on my local install with only the two modules and prereqs enabled. It didn't work out of the box, but it did work with the TimeOut set to 10000 (ten thousand).

**Comment by MangoFVTT** [comment]
@nschoenwald Alright that's good, it means it's still the same problem but the race condition is higher for other systems. Can you test with smaller values (try increments of 1000) and see roundabout where it breaks?

**Comment by nschoenwald** [comment]
10000 (ten thousand) actually does seem like the lower bound that works reliably on my local machine and my DM's server running on Oracle Cloud (with a relatively heavy module load). I tested with 5000, 7500 and 9000 and only 10000 worked reliably.

**Comment by MangoFVTT** [comment]
Great, thanks for the testing. I'll up it to 15000 to be safe on slower systems. It'll mean there's a 15seconds window at initial load where RSR doesn't block the pop-ups, but I think that's pretty reasonable. Will push a hotfix soon

**Comment by MangoFVTT** [comment]
Issue should be fixed in 3.4.7 👍

**Comment by DudeAndre** [comment]
I'm on the forge so I don't even know if I could run that kind of test. Also I'm not that techy unfortunately. I'll let you know if the fix works though

**Comment by DudeAndre** [comment]
Ok, I confirm that animations are now working without pop-ups, thank you!

**Comment by MangoFVTT** [comment]
Glad to hear it. I'll look for a cleaner solution than waiting 15 seconds eventually when I have the time, but this seems to resolve this issue for the time being 🙌

**Comment by DudeAndre** [comment]
I assure you the animations are not slow to start at all. It's all a mystery to me :)

**Comment by nschoenwald** [comment]
@DudeAndre It just takes 15 seconds after you load Foundry, not 15 seconds for every animation.

**Comment by DudeAndre** [comment]
Oh, ok, I didn't even notice that either
